'''
=================================================
Milestone 3

Nama  : Mardi Wicaksana
Batch : CODA-016-RMT

The Program created for transform data and doing Validation with great expetation to make sure the dataset is valid and ready to be analyzed
'''

GSlide = https://docs.google.com/presentation/d/13cjTErWMol2mIjd0KD2pEu6WkiRPao8nE-Upj-tH-nY/edit?slide=id.p1#slide=id.p1

##Load dataset from Kaggle

In [1]:
import kagglehub
import os
import pandas as pd
DATASET_ROOT_DIR = "opt/airflow/data/"


path = kagglehub.dataset_download("sharmajicoder/amazon-e-commerce")
print("Path to dataset files:", path)
if not os.path.exists(DATASET_ROOT_DIR):
    os.makedirs(DATASET_ROOT_DIR)
os.system("cp -r {}/* {}".format(path, DATASET_ROOT_DIR))
print("Path to dataset files:", path)

Using Colab cache for faster access to the 'amazon-e-commerce' dataset.
Path to dataset files: /kaggle/input/amazon-e-commerce
Path to dataset files: /kaggle/input/amazon-e-commerce

In [2]:
df = pd.read_csv('/content/opt/airflow/data/amazon_ecommerce_1M.csv', encoding = "ISO-8859-1")
##script untuk bikin datamart
df.head()

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.31,4.9,43,71,S2679,4.3,2025-03-04,6,Bangalore,Tablet,UPI,True,Returned
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.73,3.9,13,119,S9279,4.9,2025-12-12,1,Delhi,Tablet,UPI,True,Returned
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10919.43,4.2,46,229,S5557,4.9,2024-04-25,1,Chennai,Mobile App,Credit Card,True,Returned
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.91,3.8,6,52,S2519,3.1,2025-12-18,2,Mumbai,Web,UPI,False,In Transit
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.58,4.0,48,274,S3045,2.6,2024-05-16,5,Delhi,Web,UPI,False,Delayed

In [3]:
df.shape

(1000000, 20)

In [4]:
df.isna().sum()

user_id               0
product_id            0
category              0
subcategory           0
brand                 0
price                 0
discount              0
final_price           0
rating                0
review_count          0
stock                 0
seller_id             0
seller_rating         0
purchase_date         0
shipping_time_days    0
location              0
device                0
payment_method        0
is_returned           0
delivery_status       0
dtype: int64

In [5]:
df[df.duplicated()].sum()

user_id                 0
product_id              0
category                0
subcategory             0
brand                   0
price                 0.0
discount              0.0
final_price           0.0
rating                0.0
review_count            0
stock                   0
seller_id               0
seller_rating         0.0
purchase_date           0
shipping_time_days      0
location                0
device                  0
payment_method          0
is_returned             0
delivery_status         0
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 20 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   user_id             1000000 non-null  object
 1   product_id          1000000 non-null  object
 2   category            1000000 non-null  object
 3   subcategory         1000000 non-null  object
 4   brand               1000000 non-null  object
 5   price               1000000 non-null  float64
 6   discount            1000000 non-null  float64
 7   final_price         1000000 non-null  float64
 8   rating              1000000 non-null  float64
 9   review_count        1000000 non-null  int64
 10  stock               1000000 non-null  int64
 11  seller_id           1000000 non-null  object
 12  seller_rating       1000000 non-null  float64
 13  purchase_date       1000000 non-null  object
 14  shipping_time_days  1000000 non-null  int64
 15  location            1000000 non-null  object
 16  device              1000000 non-null  object
 17  payment_method      1000000 non-null  object
 18  is_returned         1000000 non-null  bool
 19  delivery_status     1000000 non-null  object
dtypes: bool(1), float64(5), int64(3), object(11)
memory usage: 145.9+ MB

##Transform

In [7]:
df['purchase_date'] = pd.to_datetime(df['purchase_date'])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 20 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   user_id             1000000 non-null  object
 1   product_id          1000000 non-null  object
 2   category            1000000 non-null  object
 3   subcategory         1000000 non-null  object
 4   brand               1000000 non-null  object
 5   price               1000000 non-null  float64
 6   discount            1000000 non-null  float64
 7   final_price         1000000 non-null  float64
 8   rating              1000000 non-null  float64
 9   review_count        1000000 non-null  int64
 10  stock               1000000 non-null  int64
 11  seller_id           1000000 non-null  object
 12  seller_rating       1000000 non-null  float64
 13  purchase_date       1000000 non-null  object
 14  shipping_time_days  1000000 non-null  int64
 15  location            1000000 non-null  object
 16  device              1000000 non-null  object
 17  payment_method      1000000 non-null  object
 18  is_returned         1000000 non-null  bool
 19  delivery_status     1000000 non-null  object
dtypes: bool(1), float64(5), int64(3), object(11)
memory usage: 145.9+ MB

In [9]:
df.describe()

,price,discount,final_price,rating,review_count,stock,seller_rating,shipping_time_days
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,13224.119093,28.996161,9938.876985,3.927226,32.626704,250.023345,3.750030,3.166389
std,18079.626921,14.681077,14271.885557,0.519443,43.382201,144.567038,0.722092,1.674178
min,200.030000,5.000000,101.460000,1.500000,0.000000,0.000000,2.500000,1.000000
25%,2700.147500,16.910000,1705.930000,3.600000,10.000000,125.000000,3.100000,2.000000
50%,4971.830000,28.070000,3790.795000,3.900000,20.000000,250.000000,3.800000,3.000000
75%,14134.482500,39.240000,10384.440000,4.300000,39.000000,375.000000,4.400000,5.000000
max,79999.700000,70.000000,75831.110000,5.000000,3408.000000,500.000000,5.000000,6.000000

## Great Expectation

In [10]:
!pip install great-expectations==0.18.15 ##Instal great expectation

Collecting great-expectations==0.18.15
  Downloading great_expectations-0.18.15-py3-none-any.whl.metadata (8.8 kB)
Collecting altair<5.0.0,>=4.2.1 (from great-expectations==0.18.15)
  Downloading altair-4.2.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: Click>=7.1.2 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (8.3.3)
Collecting colorama>=0.4.3 (from great-expectations==0.18.15)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: cryptography>=3.2 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (43.0.3)
Requirement already satisfied: Ipython>=7.16.3 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (7.34.0)
Requirement already satisfied: ipywidgets>=7.5.1 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (7.7.1)
Requirement already satisfied: jinja2>=2.10 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (3.1.6)
Requirement already satisfied: jsonpatch>=1.22 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (1.33)
Requirement already satisfied: jsonschema>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (4.26.0)
Collecting makefun<2,>=1.7.0 (from great-expectations==0.18.15)
  Downloading makefun-1.16.0-py2.py3-none-any.whl.metadata (2.9 kB)
Collecting marshmallow<4.0.0,>=3.7.1 (from great-expectations==0.18.15)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: mistune>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (3.2.0)
Requirement already satisfied: nbformat>=5.0 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (5.10.4)
Requirement already satisfied: notebook>=6.4.10 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (6.5.7)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (26.1)
Requirement already satisfied: pydantic>=1.9.2 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (2.12.3)
Requirement already satisfied: pyparsing>=2.4 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (3.3.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (2.9.0.post0)
Requirement already satisfied: pytz>=2021.3 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (2025.2)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (2.32.4)
Collecting ruamel.yaml<0.17.18,>=0.16 (from great-expectations==0.18.15)
  Downloading ruamel.yaml-0.17.17-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (1.16.3)
Requirement already satisfied: tqdm>=4.59.0 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (4.67.3)
Requirement already satisfied: typing-extensions>=3.10.0.0 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (4.15.0)
Requirement already satisfied: tzlocal>=1.2 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (5.3.1)
Requirement already satisfied: urllib3>=1.26 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (2.5.0)
Collecting numpy<2.0.0,>=1.22.4 (from great-expectations==0.18.15)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.4 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from great-expectations==0.18.15) (2.2.2)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from altair<5.0.0,>=4.2.1->great-expectations==0.18.15) (0.4)
Requirement already satisfied: toolz in /usr/local/lib/python3.12/dist-packages (from altair<5.0.0,>=4.2.1->great-expectations==0.18.15) (0.12.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=3.2->great-expectations==0.18.15) (2.0.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great-expectations==0.18.15) (75.2.0)
Collecting jedi>=0.16 (from Ipython>=7.16.3->great-expectations==0.18.15)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great-expectations==0.18.15) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great-expectations==0.18.15) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great-expectations==0.18.15) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great-expectations==0.18.15) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great-expectations==0.18.15) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great-expectations==0.18.15) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great-expectations==0.18.15) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from Ipython>=7.16.3->great-expectations==0.18.15) (4.9.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->great-expectations==0.18.15) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->great-expectations==0.18.15) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->great-expectations==0.18.15) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.5.1->great-expectations==0.18.15) (3.0.16)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.10->great-expectations==0.18.15) (3.0.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch>=1.22->great-expectations==0.18.15) (3.1.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.5.1->great-expectations==0.18.15) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.5.1->great-expectations==0.18.15) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.5.1->great-expectations==0.18.15) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.5.1->great-expectations==0.18.15) (0.30.0)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat>=5.0->great-expectations==0.18.15) (2.21.2)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat>=5.0->great-expectations==0.18.15) (5.9.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great-expectations==0.18.15) (6.5.1)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great-expectations==0.18.15) (26.2.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great-expectations==0.18.15) (25.1.0)
Requirement already satisfied: jupyter-client<8,>=5.3.4 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great-expectations==0.18.15) (7.4.9)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great-expectations==0.18.15) (7.17.1)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great-expectations==0.18.15) (1.6.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great-expectations==0.18.15) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great-expectations==0.18.15) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great-expectations==0.18.15) (0.25.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.4.10->great-expectations==0.18.15) (1.3.3)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->great-expectations==0.18.15) (2026.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->great-expectations==0.18.15) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->great-expectations==0.18.15) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=1.9.2->great-expectations==0.18.15) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.1->great-expectations==0.18.15) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->great-expectations==0.18.15) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->great-expectations==0.18.15) (3.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20->great-expectations==0.18.15) (2026.4.22)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=3.2->great-expectations==0.18.15) (3.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->great-expectations==0.18.15) (1.8.15)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5.1->great-expectations==0.18.15) (5.9.5)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->Ipython>=7.16.3->great-expectations==0.18.15) (0.8.6)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat>=5.0->great-expectations==0.18.15) (4.9.6)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.4.10->great-expectations==0.18.15) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=6.4.10->great-expectations==0.18.15) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.4.10->great-expectations==0.18.15) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.4.10->great-expectations==0.18.15) (0.3.0)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.4.10->great-expectations==0.18.15) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.4.10->great-expectations==0.18.15) (1.5.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->Ipython>=7.16.3->great-expectations==0.18.15) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->Ipython>=7.16.3->great-expectations==0.18.15) (0.6.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=6.4.10->great-expectations==0.18.15) (25.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=6.4.10->great-expectations==0.18.15) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=6.4.10->great-expectations==0.18.15) (1.4.0)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (2.14.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=6.4.10->great-expectations==0.18.15) (2.8.3)
Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (4.13.0)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (0.5.4)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (7.7.0)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (1.9.0)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (6.0.3)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (0.1.1)
Requirement already satisfied: fqdn in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (1.5.1)
Requirement already satisfied: isoduration in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (20.11.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (1.1.0)
Requirement already satisfied: uri-template in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (25.10.0)
Requirement already satisfied: lark>=1.2.2 in /usr/local/lib/python3.12/dist-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (1.3.1)
Requirement already satisfied: arrow>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.4.10->great-expectations==0.18.15) (1.4.0)
Downloading great_expectations-0.18.15-py3-none-any.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 83.2 MB/s eta 0:00:00
Downloading altair-4.2.2-py3-none-any.whl (813 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 813.6/813.6 kB 37.5 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading makefun-1.16.0-py2.py3-none-any.whl (22 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 3.0 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 47.0 MB/s eta 0:00:00
Downloading ruamel.yaml-0.17.17-py3-none-any.whl (109 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.1/109.1 kB 6.5 MB/s eta 0:00:00
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 51.4 MB/s eta 0:00:00
Installing collected packages: makefun, ruamel.yaml, numpy, marshmallow, jedi, colorama, altair, great-expectations
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: altair
    Found existing installation: altair 5.5.0
    Uninstalling altair-5.5.0:
      Successfully uninstalled altair-5.5.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.

In [10]:
# Create a data context

from great_expectations.data_context import FileDataContext

context = FileDataContext.create(project_root_dir='./')

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/great_expectations/data_context/store/_store_backend.py:90: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parsed_store_backend_id = store_backend_id_file_parser.parseString(

In [11]:
datasource_name = 'amazon_datasource'
datasource = context.sources.add_pandas(datasource_name)

asset_name = 'amazon_ecommerce_data'
path_to_data = '/content/opt/airflow/data/amazon_ecommerce_1M.csv'

asset = datasource.add_csv_asset(
    name=asset_name,
    filepath_or_buffer=path_to_data
)

batch_request = asset.build_batch_request()

In [12]:
# Create expectation suite
expectation_suite_name = 'amazon_suite'
context.add_or_update_expectation_suite(expectation_suite_name)

# Create validator
validator = context.get_validator(batch_request=batch_request, expectation_suite_name=expectation_suite_name)

# Check data
validator.head()

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
0,U356787,P39256,Electronics,Mobile,H&M,33090.51,10.46,29629.31,4.9,43,71,S2679,4.3,2025-03-04,6,Bangalore,Tablet,UPI,True,Returned
1,U198246,P38657,Sports,Outdoor,Samsung,9368.97,5.32,8870.73,3.9,13,119,S9279,4.9,2025-12-12,1,Delhi,Tablet,UPI,True,Returned
2,U539898,P38893,Sports,Fitness,H&M,14756.85,26.00,10919.43,4.2,46,229,S5557,4.9,2024-04-25,1,Chennai,Mobile App,Credit Card,True,Returned
3,U325772,P54118,Beauty,Makeup,Sony,668.83,24.81,502.91,3.8,6,52,S2519,3.1,2025-12-18,2,Mumbai,Web,UPI,False,In Transit
4,U865179,P70217,Home,Decor,Sony,10881.29,48.63,5589.58,4.0,48,274,S3045,2.6,2024-05-16,5,Delhi,Web,UPI,False,Delayed

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [13]:
validator.expect_column_values_to_be_unique("user_id") ## 1. checking user_id is unique

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

{
  "success": false,
  "expectation_config": {
    "expectation_type": "expect_column_values_to_be_unique",
    "kwargs": {
      "column": "user_id",
      "batch_id": "amazon_datasource-amazon_ecommerce_data"
    },
    "meta": {}
  },
  "result": {
    "element_count": 1000000,
    "unexpected_count": 670255,
    "unexpected_percent": 67.02550000000001,
    "partial_unexpected_list": [
      "U356787",
      "U198246",
      "U539898",
      "U325772",
      "U705397",
      "U498591",
      "U738720",
      "U330283",
      "U665158",
      "U166613",
      "U887352",
      "U492077",
      "U351083",
      "U847581",
      "U454508",
      "U132938",
      "U858490",
      "U939482",
      "U361941",
      "U163918"
    ],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 67.02550000000001,
    "unexpected_percent_nonmissing": 67.02550000000001
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [14]:
validator.expect_column_values_to_be_between('rating', min_value=1, max_value=5) #2 Rating must be range 1 - 5

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

{
  "success": true,
  "expectation_config": {
    "expectation_type": "expect_column_values_to_be_between",
    "kwargs": {
      "min_value": 1,
      "max_value": 5,
      "column": "rating",
      "batch_id": "amazon_datasource-amazon_ecommerce_data"
    },
    "meta": {}
  },
  "result": {
    "element_count": 1000000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [19]:
validator.expect_column_values_to_be_in_set("payment_method", ["UPI", "Credit Card", "Debit Card", "Cash on Delivery"]) ##3. Check payment method must be UPI,credit card, debit card, and Cash on delivery

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

{
  "success": true,
  "expectation_config": {
    "expectation_type": "expect_column_values_to_be_in_set",
    "kwargs": {
      "column": "payment_method",
      "value_set": [
        "UPI",
        "Credit Card",
        "Debit Card",
        "Cash on Delivery"
      ],
      "batch_id": "amazon_datasource-amazon_ecommerce_data"
    },
    "meta": {}
  },
  "result": {
    "element_count": 1000000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [18]:
validator.expect_column_values_to_be_in_type_list('stock', ['int']) ##4. stock must be integer

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Calculating Metrics:   0%|          | 0/1 [00:00<?, ?it/s]

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

{
  "success": true,
  "expectation_config": {
    "expectation_type": "expect_column_values_to_be_in_type_list",
    "kwargs": {
      "column": "stock",
      "type_list": [
        "int"
      ],
      "batch_id": "amazon_datasource-amazon_ecommerce_data"
    },
    "meta": {}
  },
  "result": {
    "observed_value": "int64"
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [17]:
validator.expect_column_values_to_not_be_in_set("price", [0]) ##5 Price cannot be 0

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

{
  "success": true,
  "expectation_config": {
    "expectation_type": "expect_column_values_to_not_be_in_set",
    "kwargs": {
      "column": "price",
      "value_set": [
        0
      ],
      "batch_id": "amazon_datasource-amazon_ecommerce_data"
    },
    "meta": {}
  },
  "result": {
    "element_count": 1000000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [16]:
validator.expect_column_value_lengths_to_be_between('brand', min_value=2) #6  ##Brand minimum Character Must be 2 Character

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/9 [00:00<?, ?it/s]

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

{
  "success": true,
  "expectation_config": {
    "expectation_type": "expect_column_value_lengths_to_be_between",
    "kwargs": {
      "min_value": 2,
      "column": "brand",
      "batch_id": "amazon_datasource-amazon_ecommerce_data"
    },
    "meta": {}
  },
  "result": {
    "element_count": 1000000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [15]:
validator.expect_column_values_to_match_strftime_format("purchase_date", "%Y-%m-%d") ##Purchase date must be YYYY-MM-DD

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

{
  "success": true,
  "expectation_config": {
    "expectation_type": "expect_column_values_to_match_strftime_format",
    "kwargs": {
      "column": "purchase_date",
      "strftime_format": "%Y-%m-%d",
      "batch_id": "amazon_datasource-amazon_ecommerce_data"
    },
    "meta": {}
  },
  "result": {
    "element_count": 1000000,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}

In [20]:
df.to_csv("P2M3_Mardi_Wicaksana_data_raw.csv") ##Save data to csv

In [21]:
# Create a checkpoint

checkpoint_1 = context.add_or_update_checkpoint(
    name = 'checkpoint_1',
    validator = validator,
)

In [22]:
# Run a checkpoint

checkpoint_result = checkpoint_1.run()

WARNING:py.warnings:/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Calculating Metrics: 0it [00:00, ?it/s]

In [23]:
# Build data docs

context.build_data_docs()

{'local_site': 'file:///content/gx/uncommitted/data_docs/local_site/index.html'}